### ISSUE TITLE
please tell me how to run the code? or the  software  requirement

### ISSUE THREAD

**Issue by wn312991** [subodh-malgonde/vehicle-detection#1]
please tell me how to run the code? just run Vehicle_Detection.ipynb,  and what is the software requirement? @subodh-malgonde

**Comment by subodh-malgonde** [comment]
Just added a `environment.yml` file. If you use Anaconda to manage environments you can clone the environment (i.e. install the dependencies) by typing

    conda env create -f environment.yml

Once you install the dependencies you can type `source activate keras` (keras is the name of the environment in `environment.yml`

You just have to run all the cells in Vehicle_Detection.ipynb, there is no other code. In the notebook there are code blocks to test the model on a few test images and also on the video.

**Comment by wn312991** [comment]
@subodh-malgonde firstly , sincerely thanks you for your reply,secondly,  I don't use Anaconda to manage  environment,and I will try it later,thirdly,I want to consult you that does this code apply to other road video?  What is the accuracy rate？

**Comment by subodh-malgonde** [comment]
You are welcome.

What do you mean by other video? I used this model to process `project_video.mp4`. I have not tried it yet for other road videos. To measure accuracy you need the ground truth as well (i.e. video with bounding boxes for each frame).

**Comment by wn312991** [comment]
@subodh-malgonde  hello,dear subodh-malgonde,when I type conda env create -f environment.yml,conda environments are currently broken,the error : $ conda create --file environment.yml 
Error: Can't process without a name environment.yml is not a valid yaml file. 
Environment with requierements.txt file needs a name 。
Have you ever had this problem? how to solve it?thanks you very much

**Comment by subodh-malgonde** [comment]
Sorry I forgot about this. I have never seen this issue. Maybe you could take the dependencies from `environment.yml` and build a `yaml` file yourself. As explained here https://conda.io/docs/using/envs.html

**Comment by wn312991** [comment]
I have tried it before as the webside you offered but it didn't succeed,I am very confused @subodh-malgonde

**Comment by wn312991** [comment]
Tn  environment.yml,  it included: name: C:\Anaconda3\envs\tensorflow
dependencies:
- decorator=4.0.11=py35_0
- ipython_genutils=0.1.0=py35_0
- jsonschema=2.5.1=py35_0
- jupyter_core=4.3.0=py35_0
- nbformat=4.3.0=py35_0
- pip=9.0.1=py35_1
- python=3.5.3=0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- traitlets=4.3.2=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-core==4.3.0
but when I run the Vehicle-Detection.ipydb,the first cell import error: 
ImportError                               Traceback (most recent call last)
<ipython-input-1-7910e7e534f5> in <module>()
----> 1 import cv2
      2 import numpy as np
      3 import matplotlib.pyplot as plt
      4 import matplotlib.image as mpimg
      5 import glob

ImportError: DLL load failed: 找不到指定的模块。

have you ever met this problem?please help  @subodh-malgonde @ryan-keenan 
> ``

**Comment by subodh-malgonde** [comment]
@wn13083405221 Are you a Udacity student? If yes then can you post this on the [Udacity forum](https://discussions.udacity.com)?

This looks like some windows setup issue.You can also try submitting an issue to Conda's github repository https://github.com/conda/conda

**Comment by san-rs** [comment]
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ......ERROR requests.packages.urllib3.connection:_match_hostname(317): Certificate did not match expected hostname: conda.binstar.org. Certificate: {'subject': ((('organizationalUnitName', 'Domain Control Validated'),), (('organizationalUnitName', 'PositiveSSL Multi-Domain'),), (('commonName', 'anaconda.com'),)), 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Domain Validation Secure Server CA'),)), 'notBefore': 'Apr 28 00:00:00 2017 GMT', 'OCSP': ('http://ocsp.comodoca.com',), 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl',), 'subjectAltName': (('DNS', 'anaconda.com'), ('DNS', 'anacondacloud.com'), ('DNS', 'anacondacloud.org'), ('DNS', 'binstar.org'), ('DNS', 'wakari.io')), 'caIssuers': ('http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt',), 'serialNumber': '67DECDFB7CCA3B7951249D6BEB13DE22', 'notAfter': 'Sep 29 23:59:59 2017 GMT', 'version': 3}
SSL verification error: hostname 'conda.binstar.org' doesn't match either of 'anaconda.com', 'anacondacloud.com', 'anacondacloud.org', 'binstar.org', 'wakari.io'
ERROR requests.packages.urllib3.connection:_match_hostname(317): Certificate did not match expected hostname: conda.binstar.org. Certificate: {'subject': ((('organizationalUnitName', 'Domain Control Validated'),), (('organizationalUnitName', 'PositiveSSL Multi-Domain'),), (('commonName', 'anaconda.com'),)), 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Domain Validation Secure Server CA'),)), 'notBefore': 'Apr 28 00:00:00 2017 GMT', 'OCSP': ('http://ocsp.comodoca.com',), 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl',), 'subjectAltName': (('DNS', 'anaconda.com'), ('DNS', 'anacondacloud.com'), ('DNS', 'anacondacloud.org'), ('DNS', 'binstar.org'), ('DNS', 'wakari.io')), 'caIssuers': ('http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt',), 'serialNumber': '67DECDFB7CCA3B7951249D6BEB13DE22', 'notAfter': 'Sep 29 23:59:59 2017 GMT', 'version': 3}
.SSL verification error: hostname 'conda.binstar.org' doesn't match either of 'anaconda.com', 'anacondacloud.com', 'anacondacloud.org', 'binstar.org', 'wakari.io'
....
Solving package specifications: .
NoPackagesFoundError: Packages missing in current linux-64 channels: 
  - appnope 0.1.0 py35_0
  - opencv3 3.1.0 py35_0
  - tbb 4.3_20141023 0



What do I do Subodh?

**Comment by subodh-malgonde** [comment]
@suraj-ravishankar As the error says, these packages were not installed by Anaconda:

1. appnope 0.1.0 py35_0
2. opencv3 3.1.0 py35_0
3. tbb 4.3_20141023 0

If you can install these packages manually yourself. Just google "How to install opencv3 on linux 64 bit?"
