### ISSUE TITLE
Bounding boxes not showing

### ISSUE THREAD

**Issue by aashay96** [subodh-malgonde/vehicle-detection#2]
Hey, I ran the code, and the bounding boxes show up for only very small thresholds like 0.007 that too randomly placed. Please help.

**Comment by subodh-malgonde** [comment]
Are your pre-processing the test images before passing them to the model?

You can have a look at [Vehicle_Detection.ipynb](https://github.com/subodh-malgonde/vehicle-detection/blob/master/Vehicle_Detection.ipynb), I have run the model on some test images and its working fine for me.

**Comment by aashay96** [comment]
Yes. I am doing pre- processing and using the same model as yours. The issue still exist. Can it have something to do with the weights?

**Comment by subodh-malgonde** [comment]
Could be. I hope you are using these weights https://drive.google.com/file/d/0B1tW_VtY7onibmdQWE1zVERxcjQ/view?usp=sharing

Are you using `cv2` to read images or `matplotlib`? `cv2` will read images in the `BGR` format whereas `matplotlib` will read them in `RGB`. The model is trained on `RGB` images. So you will have to ensure you are passing `RGB` image for testing.

**Comment by aashay96** [comment]
I am using matplotlib. I copied exactly your code, and used the mentioned weight, but the problem still exists.

**Comment by subodh-malgonde** [comment]
Can you upload your code somewhere and give me a link?

**Comment by aashay96** [comment]
sure. Here is the link to the code, though I copied your code, and tried, still the same issue.
http://paste.ubuntu.com/24253759/

**Comment by antonyjjoseph** [comment]
Hi Subodh, 
I am also facing the same issue. Boxes[] return 0 items. Any idea, what could be the problem. Kindly help me.

**Comment by antonyjjoseph** [comment]
When I debug the program, none of the confidence score for class 'car' goes more than threshold(0.25 or 0.20). The maximum confidence score for class 'car' is only 0.006. I am using the same 'yolo-tiny.weights'. Please help.

**Comment by Angloher** [comment]
I am having the same issue

**Comment by ManjeeraJagiri** [comment]
Hey, I am facing the same issue. Did anyone figure out the problem?

**Comment by docPhil99** [comment]
I had this problem. I think the Keras 2 API is the problem. I used the solution [here ](https://github.com/xslittlegrass/CarND-Vehicle-Detection/issues/3) and now it works

**Comment by anandkoirala** [comment]
following worked for me
comment by mark-chan https://github.com/xslittlegrass/CarND-Vehicle-Detection/issues/3
add this code before the load_weights(model,'./yolo-tiny.weights') function...

**Comment by ManjeeraJagiri** [comment]
@docPhil99 @anandkoirala Worked like a charm! Thanks a lot. Have any of you tried training with custom dataset?

**Comment by subodh-malgonde** [comment]
I would just like to mention that this repository uses keras 1.2.1 and tensorflow 0.12.1. If you use Keras 2.x or tensorflow 1.x you may need to modify the code.
