### ISSUE TITLE
about the moviepy 

### ISSUE THREAD

**Issue by XiongLianga** [subodh-malgonde/vehicle-detection#4]
At the end of Vehicle_Detection.ipynb，you deal with the videos by using the  moviepy. However, i can't find the document of moviepy, can you tell me how to deal with the problem? Thank you so much.

**Comment by subodh-malgonde** [comment]
Moviepy is a python library. You need to install it. You can either install using `pip` or `conda`. The version which was used by me is `moviepy==0.2.2.13`. You can find this in the environment.yml file in this repository.

**Comment by XiongLianga** [comment]
thank you for your solution.
