### ISSUE TITLE
packages are not found 

### ISSUE THREAD

**Issue by madhu-korada** [subodh-malgonde/vehicle-detection#7]
i tried to do  conda env create -f environment.yml
but i got this .any solution??

ResolvePackageNotFound:
  - pexpect==4.0.1=py35_0
  - appnope==0.1.0=py35_0
  - sqlite==3.13.0=0
  - tk==8.5.18=0
  - icu==54.1=0
  - openssl==1.0.2j=0
  - tensorflow==0.11.0=py35_0
  - zlib==1.2.8=3
  - ptyprocess==0.5.1=py35_0
  - readline==6.2=2
  - mkl==11.3.3=0
  - tbb==4.3_20141023=0
  - qt==5.6.2=0
  - protobuf==3.0.0=py35_0
  - hdf5==1.8.17=1
  - terminado==0.6=py35_0
  - freetype==2.5.5=1
  - libpng==1.6.27=0

**Comment by subodh-malgonde** [comment]
What is your OS? I can't think of a reason why conda is not able to find these packages. You can try installing these packages manually by doing `conda install package_name`

**Comment by vieite** [comment]
I'm on ubuntu and also got some issues wuth some packages
~/vehicle-detection$ conda env create -f environment.yml


Solving environment: failed

ResolvePackageNotFound: 
  - tbb==4.3_20141023=0
  - appnope==0.1.0=py35_0


I also tried your solution. It worked with tbb but not with appnote so I deleted it from the environment.yml but when I run Vehicle_Detection.ipynb I get 
ModuleNotFoundError: No module named 'cv2'

Just noticed I missed a step but found another error
~/vehicle-detection$ source activate keras
Could not find conda environment: keras
You can list all discoverable environments with `conda info --envs`.

**Comment by subodh-malgonde** [comment]
> You can list all discoverable environments with conda info --envs

Can you try the above command and check if the environment `keras` was created or not? If you read through the `environment.yml` file, at the top it has this line:

    name: keras

Which means when you create a conda environment using this file, then the name of the environment will be "keras". If there is no such environment then it could one of the 2 things:

1. Either your command was not executed properly
2. Or the environment has been created but`conda` is not looking for the environments in the right place. In this case you would have to do some googling to figure out how to specify the conda path.

Also I should mention that I am running OSX 64 bit operating system with Python 3.5. Check if the packages listed in the `environment.yml` file are available for your OS or not.
